version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/data/:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend/:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  # test:
  #   build: ./backend
  #   volumes:
  #     - ./backend:/app
  #   command: bundle exec rspec spec  